### ISSUE TITLE
Key can be anything, even empty

### ISSUE THREAD

**Issue by Edmartt** [golang-jwt/jwt#283] opened 2023-03-06 17:55 UTC
https://github.com/golang-jwt/jwt/blob/0d2f0d4809b8a7e01b0cb27cbfde79a69cb2a298/token.go#L71

I think this line needs to be validated because I was making a mistake here, forgot to set env var and even like that the key string travels empty and it's assigned. I'm not sure if this is just my fault and a trivial thing but if not, It's a thing to be careful about.

i.e if you turn the secret key into bytes(array) the array will be empty

For refererences, look at this:

https://github.com/Edmartt/go-authentication-api/blob/745596863a538ffcbbc718c6519bff0dabd1d4e8/pkg/jwt/jwt.go#L19

**Comment by Edmartt** [comment] 2023-03-06 18:46
I realized that even when SignedString method has interface as param, if you don't send a bytes array, the returned value is an empty string


![imagen](https://user-images.githubusercontent.com/47486245/223202462-3457d631-409e-4abe-abd4-93c4a6b80727.png)

**Comment by oxisto** [comment] 2023-03-25 14:49
Hi @Edmartt 

There are two issues here

1. Regarding your first post: yes, we do not really check whether you pass an empty array as a key. This is somewhat in the responsibility of the caller. Because of course we could check if it is empty, but then we could argue that a key of size 1 is also not suitable, etc.

2. Yes, because of the way the API works (it was built back when we did not have generics in Go), the key can be `any` or `interface{}`. So yes you can pass in a `string`. BUT, you will get an error `"key is of invalid type"` (`ErrInvalidKeyType`) and the token will be empty. So in your second example, yes the token is empty, but you also ignored the error value.

**Comment by mfridman** [comment] 2023-07-14 23:23
I think this is working as intended, so closing the issue. But feel free to continue the discussion.

Agree with the points Christian mentioned above, although checking for the error won't help here since `token.SignedString([]byte(""))` is valid, unfortunately. So ensuring you have a valid key non-empty is very important.

---

Side note, it's a Go best practice to check for errors and avoid using return values if `err != nil`, so this bit:

```go
func X() (tokenString string, err error) { 
  tokenString, tokenError := token.SignedString(secretKeyBytes)
  if tokenError != nil{
    return
  }
}
```

should really be returning an error instead of a named return (which will be `nil`). E.g.,

```go
func X() (string, error) { 
  tokenString, err := token.SignedString(secretKeyBytes)
  if err != nil{
    // let the caller gracefully handle the error
    // https://go.dev/doc/effective_go#errors
    return "", err
  }
  // use return value only once we checked for an error
  return tokenString, nil
}
```

**Closed by mfridman** 2023-07-14 23:23 UTC
