### ISSUE TITLE
v3.2.2+incompatible build have error

### ISSUE THREAD

**Issue by 4color** [golang-jwt/jwt#90] opened 2021-08-17 10:22 UTC
github.com/golang-jwt/jwt
../pkg/mod/github.com/golang-jwt/jwt@v3.2.2+incompatible/ecdsa.go:135:4: r.FillBytes undefined (type *big.Int has no field or method FillBytes)
../pkg/mod/github.com/golang-jwt/jwt@v3.2.2+incompatible/ecdsa.go:136:4: s.FillBytes undefined (type *big.Int has no field or method FillBytes)

**Comment by oxisto** [comment] 2021-08-17 10:51
Duplicate of https://github.com/golang-jwt/jwt/issues/50

Starting with `v3.2.2`, jwt-go required at least Go 1.15.

**Comment by mfridman** [comment] 2021-08-18 13:22
Please consider updating your Go version if possible. Closing as no further action.

**Closed by mfridman** 2021-08-18 13:22 UTC
